In [2]:
#inisialisasi library yang dibutuhkan

import numpy as np #untuk operasi vektor dan matriks

<h1>#Soal No 1 </br></h1>

Given the following 4x4 grayscale image, perform the following operations and provide the resulting 4 x4 image. </br>

<ol>a). flip </ol>
<ol>b). flop </ol>
<ol>c). flip-flop </ol>
<ol>d). invert and </ol>
<ol>e). rotate clockwise by 90 degrees. </ol></br>

$$
\begin{bmatrix}
176 & \; 94 & \; 201 & \; 219 \\
37 & \; 161 & \; 16 & \; 88 \\
71 & \; 129 & \; 177 & \; 81 \\
41 & \; 198 & \; 107 & \; 19
\end{bmatrix}
$$



In [3]:
# soal a  flip
"""
terdapat 2 cara untuk melakukan flip pada matriks

"""
row = 4
col = 4

#inisiasi matrix
list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")
# cara 1 memakai matrix identitas dengan diagonal non utama

#membuat matriks identitas
I = np.eye(row)

#membuat matriks transformasi
m_trnf = np.fliplr(I)
print("Matrix transformation : ")
print(m_trnf, "\n")

#flip matrix 
"""
X' = X * M  
"""
flip_mtrx = np.dot(soal_mtrx, m_trnf)
print('Matrix Flip cara 1 : ')
print(flip_mtrx, "\n")


#caras 2 

flip_mtrx2 = soal_mtrx[:, ::-1] #menjadikan urutan dalam setiap baris matrix menjadi terbalik 
print('Matrix Flip cara 2 : ')
print(flip_mtrx2, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix transformation : 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Matrix Flip cara 1 : 
[[219. 201.  94. 176.]
 [ 88.  16. 161.  37.]
 [ 81. 177. 129.  71.]
 [ 19. 107. 198.  41.]] 

Matrix Flip cara 2 : 
[[219 201  94 176]
 [ 88  16 161  37]
 [ 81 177 129  71]
 [ 19 107 198  41]] 



In [4]:
# soal b flop
"""
terdapat 2 cara untuk melakukan flop pada matriks

"""
row = 4
col = 4

#inisiasi matrix
list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")
# cara 1 memakai matrix identitas dengan diagonal non utama

#membuat matriks identitas
I = np.eye(row)

#membuat matriks transformasi
m_trnf = np.fliplr(I)
print("Matrix transformation : ")
print(m_trnf, "\n")

#flop matrix 
"""
X' = M * X  
"""
flip_mtrx = np.dot(m_trnf, soal_mtrx)
print('Matrix Flop cara 1 : ')
print(flip_mtrx, "\n")


#caras 2 

flip_mtrx2 = soal_mtrx[::-1,:] #menjadikan urutan dalam setiap colom matrix menjadi terbalik 
print('Matrix Flop cara 2 : ')
print(flip_mtrx2, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix transformation : 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Matrix Flop cara 1 : 
[[ 41. 198. 107.  19.]
 [ 71. 129. 177.  81.]
 [ 37. 161.  16.  88.]
 [176.  94. 201. 219.]] 

Matrix Flop cara 2 : 
[[ 41 198 107  19]
 [ 71 129 177  81]
 [ 37 161  16  88]
 [176  94 201 219]] 



In [5]:
#C FLIP-FLOP
"""
terdapat 2 cara untuk melakukan flip-flop pada matriks

"""
row = 4
col = 4

#inisiasi matrix
list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")
# cara 1 memakai matrix identitas dengan diagonal non utama

#membuat matriks identitas
I = np.eye(row)

#membuat matriks transformasi
m_trnf = np.fliplr(I)
print("Matrix transformation : ")
print(m_trnf, "\n")

#flip-flop matrix 
"""
flip = X * M
flop = M * flip
"""


flip_mtrx = np.dot(soal_mtrx, m_trnf)
flip_flop_mtrx = np.dot(m_trnf, flip_mtrx)
print('Matrix Flip-Flop cara 1 : ')
print(flip_flop_mtrx, "\n")


#caras 2 

flip_mtrx2 = soal_mtrx[:,::-1] #menjadikan urutan dalam setiap baris matrix menjadi terbalik 
flip_flop_mtrx2 = flip_mtrx2[::-1,:] #hasil dari flip di flop 
print('Matrix Flip Flop cara 2 : ')
print(flip_flop_mtrx2, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix transformation : 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Matrix Flip-Flop cara 1 : 
[[ 19. 107. 198.  41.]
 [ 81. 177. 129.  71.]
 [ 88.  16. 161.  37.]
 [219. 201.  94. 176.]] 

Matrix Flip Flop cara 2 : 
[[ 19 107 198  41]
 [ 81 177 129  71]
 [ 88  16 161  37]
 [219 201  94 176]] 



In [6]:
#D invert
"""
2 langkah invert image :
- kalikan dengan -1 
- mapping kembali setiap nilai di dalam matrix kedalam fungsi 

F(a) = amax - a

"""
row = 4
col = 4

#inisiasi matrix
list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")

a_max = np.max(soal_mtrx)

#defenisikan fungsinya
def f(a):
    return a_max - a

#jadikan fungsi sebagai vektor
f = np.vectorize(f)

#mapping fungsi ke dalam matrix

invert_mtrx = f(soal_mtrx)

print('Matrix Invert : ')
print(invert_mtrx, "\n")


Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix Invert : 
[[ 43 125  18   0]
 [182  58 203 131]
 [148  90  42 138]
 [178  21 112 200]] 



In [7]:
#E rotate 90 der

"""
2 steo untuk melakukan rotasi 90 derajat searah jarum jam:

- Transpose matrix
- flip horizontal matrix

"""

row = 4
col = 4

#inisiasi matrix
list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")


#transpose matrix
transpose_mtrx = np.transpose(soal_mtrx)

#flip horizontal matrix
I = np.eye(row)
m_trnf = np.fliplr(I)
flip_mtrx = np.dot(transpose_mtrx, m_trnf)

print("Matrix Rotasi 90 derajat : ")
print(flip_mtrx, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix Rotasi 90 derajat : 
[[ 41.  71.  37. 176.]
 [198. 129. 161.  94.]
 [107. 177.  16. 201.]
 [ 19.  81.  88. 219.]] 



<h1>#SOAL no 2 </h1></br>

Compute the (a) <b>Sum</b>, (b) <b>difference</b> and (c) <b> absolute diference </b> the following two - <b> 8 bit Images</b></br>
using <b>saturation arithmetic</b> to <b>store</b> the result in another 8-bit image:</br>


$$
l_1 =
\begin{bmatrix}
19 & \; 171 & \; 91 & \; 68 \\
123 & \; 99 & \; 74 & \; 195 \\
85 & \; 71 & \; 208 & \; 18 \\
241 & \; 212 & \; 189 & \; 68
\end{bmatrix}
$$


$$
l_2=
\begin{bmatrix}
106 & \; 97 & \; 190 & \; 5 \\
81 & \; 64 & \; 183 & \; 82 \\
71 & \; 200 & \; 251 & \; 94 \\
181 & \; 76 & \; 9 & \; 18
\end{bmatrix}
$$

In [7]:
# inisiasi fungsi
def saturasi(x):
    if x > 255:
        return 255
    elif x < 0:
        return 0
    else:
        return x

In [9]:
# a Sum

#inisiasi matrix
list_mtrx_1 = [
    [19,171,91,68],
    [123,99,74,195],
    [85,71,208,18],
    [241,212,189,68]
]

list_mtrx_2 =[
    [106,97,190,5],
    [81,64,183,82],
    [71,200,251,94],
    [181,76,9,18]
]

mtrx_1 = np.array(list_mtrx_1)
mtrx_2 = np.array(list_mtrx_2)

#penjumlahan matrix
sum_mtrx = mtrx_1 + mtrx_2
vextor_saturasi = np.vectorize(saturasi)
sum_mtrx = vextor_saturasi(sum_mtrx)

print("Matrix Sum : ")
print(sum_mtrx, "\n")

Matrix Sum : 
[[125 255 255  73]
 [204 163 255 255]
 [156 255 255 112]
 [255 255 198  86]] 



In [10]:
# b difference
#inisiasi matrix
list_mtrx_1 = [
    [19,171,91,68],
    [123,99,74,195],
    [85,71,208,18],
    [241,212,189,68]
]

list_mtrx_2 =[
    [106,97,190,5],
    [81,64,183,82],
    [71,200,251,94],
    [181,76,9,18]
]

mtrx_1 = np.array(list_mtrx_1)
mtrx_2 = np.array(list_mtrx_2)

#penmgurangan matrix
diff_mtrx = mtrx_1 - mtrx_2
vextor_saturasi = np.vectorize(saturasi)
diff_mtrx = vextor_saturasi(diff_mtrx)

print("Matrix Difference : ")
print(diff_mtrx, "\n")

Matrix Difference : 
[[  0  74   0  63]
 [ 42  35   0 113]
 [ 14   0   0   0]
 [ 60 136 180  50]] 



In [11]:
# C  DIFFERENCE ABSOLUTE

#inisiasi matrix
list_mtrx_1 = [
    [19,171,91,68],
    [123,99,74,195],
    [85,71,208,18],
    [241,212,189,68]
]

list_mtrx_2 =[
    [106,97,190,5],
    [81,64,183,82],
    [71,200,251,94],
    [181,76,9,18]
]

mtrx_1 = np.array(list_mtrx_1)
mtrx_2 = np.array(list_mtrx_2)

#penmgurangan ABSOLUTE matrix
diff_mtrx_abs = abs(mtrx_1 - mtrx_2)
vextor_saturasi = np.vectorize(saturasi)
diff_mtrx_abs = vextor_saturasi(diff_mtrx_abs)

print("Matrix Difference Absolute : ")
print(diff_mtrx_abs, "\n")

Matrix Difference Absolute : 
[[ 87  74  99  63]
 [ 42  35 109 113]
 [ 14 129  43  76]
 [ 60 136 180  50]] 



<h1>#SOAL no 3</h1></br>

given the following 4 x 4 grayscale image, perform the following operations: </br>
<ol>a). <b>Downsample</b> by a factor of 2 using <b> nearest-neighbor interpolation. Provide</b> the resulting 2 x 2 image</ol>
<ol>b). <b>Downsample</b>the same image by a factor of 2 using <b> average pooling. Show</b> the resulting 2 x 2 image</ol>
<ol>c). <b>Upsample</b> the same image by a factor of 2 using <b> bilinear interpolation. Display</b> the resulting 8 x8 image</ol></br>

$$
\begin{bmatrix}
176 & \; 94 & \; 201 & \; 219 \\
37 & \; 161 & \; 16 & \; 88 \\
71 & \; 129 & \; 177 & \; 81 \\
41 & \; 198 & \; 107 & \; 19
\end{bmatrix}
$$


In [12]:
# soal a nearest-neighbor

#siapkan matrix 0 2x2

matrix_2_x_2 = np.zeros((2,2))

#matrix soal :

list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")

#lakukan iterasi untuk mengisi matrix 0 2x2 dengan matrix soal

FACTOR_SCALE = 2

for row in range(len(matrix_2_x_2)):
    for col in range(len(matrix_2_x_2[row])):
        matrix_2_x_2[row][col] = soal_mtrx[row*FACTOR_SCALE][col*FACTOR_SCALE]

print("Matrix 2x2 downsampling nearest-neighbor: ")
print(matrix_2_x_2, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix 2x2 downsampling nearest-neighbor: 
[[176. 201.]
 [ 71. 177.]] 



In [13]:
# soal b . Average pooling
#siapkan matrix 0 2x2

matrix_2_x_2 = np.zeros((2,2))

#matrix soal :

list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")

#lakukan iterasi untuk mengisi matrix 0 2x2 dengan matrix soal

FACTOR_SCALE = 2

for row in range(len(matrix_2_x_2)):
    for col in range(len(matrix_2_x_2[row])):
        matrix_2_x_2[row][col] = np.mean(soal_mtrx[row*FACTOR_SCALE:(row+1)*FACTOR_SCALE, col*FACTOR_SCALE:(col+1)*FACTOR_SCALE])

print("Matrix 2x2 downsampling average pooling: ")
print(matrix_2_x_2, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix 2x2 downsampling average pooling: 
[[117.   131.  ]
 [109.75  96.  ]] 



In [20]:
# Soal C Upsampling BIlinear interpolation 

#siapkan matrix None 8x8
matrix_8_x_8 = np.full((8, 8), -1)

list_mtrx = [
    [176,94,201,219],
    [37, 161, 16, 88],
    [71,129,177,81],
    [41,198,107,19]
]

soal_mtrx = np.array(list_mtrx)
print("Matrix soal : ")
print(soal_mtrx, "\n")


#isi matrix 8x8 dengan matrix soal 
FACTOR_SCALE = 2
for row in range(len(soal_mtrx)):
    for col in range(len(soal_mtrx[row])):
        matrix_8_x_8[row*FACTOR_SCALE][col*FACTOR_SCALE] = soal_mtrx[row][col]

#isi kolom terakhir dengan x -1,y -1
for row in range(len(matrix_8_x_8)):
    matrix_8_x_8[row][-1] = matrix_8_x_8[row][-2]

#isi matrix 8x8 dengan interpolasi bilinear
for row in range(len(matrix_8_x_8)):
    if row %2 ==0:
        for col in range(len(matrix_8_x_8[row])):
            if matrix_8_x_8[row][col] == -1:
                matrix_8_x_8[row][col] = (matrix_8_x_8[row][col-1] + matrix_8_x_8[row][col+1]) / 2

for row in range(len(matrix_8_x_8)):
    if row %2 !=0 and row != 7:
        for col in range(len(matrix_8_x_8[row])):
            if matrix_8_x_8[row][col] == -1 and col != 7:
                matrix_8_x_8[row][col] = (matrix_8_x_8[row-1][col] + matrix_8_x_8[row+1][col]) / 2
            elif col == 7:
                matrix_8_x_8[row][col] = matrix_8_x_8[row][col-1]

#isi baris terakhir dengan x -1,y -1
for col in range(len(matrix_8_x_8[0])):
    matrix_8_x_8[-1][col] = matrix_8_x_8[-2][col]

print("Matrix 8x8 upsampling Bilinear Interpolation: ")
print(matrix_8_x_8, "\n")

Matrix soal : 
[[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]] 

Matrix 8x8 upsampling Bilinear Interpolation: 
[[176 135  94 147 201 210 219 219]
 [106 117 127 117 108 131 153 153]
 [ 37  99 161  88  16  52  88  88]
 [ 54  99 145 120  96  90  84  84]
 [ 71 100 129 153 177 129  81  81]
 [ 56 109 163 152 142  96  50  50]
 [ 41 119 198 152 107  63  19  19]
 [ 41 119 198 152 107  63  19  19]] 



<h1>CATATAN</h1>:

link youtube : https://youtu.be/puY9zN5kqig </br>
assistant : chat gpt 4.0